# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf1e5085a4e0aa2dbcd298b73f2d086ef9f7dc49d84c66ad89a24dbad9876ecfe237b1f0b858477e62be36b885f28c8d2d8e5b71574ca63d4fd352b1c17cc86

test:
  secret_key_base: d2008a29b580403cea8f97b91048c351b1779cc676d7dea6de3ad7cf93815ab20866ac6c056274a8866cad53a1e254ebda4f15368b5d9fb971db35e4f44ed3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
